project_id = "dovwynkusvmwjfykkmmw"

[functions.fetch-google-places]
verify_jwt = false

[functions.rescrape-business]
verify_jwt = false

[functions.get-maps-key]
verify_jwt = false

[functions.sitemap]
verify_jwt = false
